br:
  com:
    pan:
      jwt:
        secret: CF9234E57F5BB51458127AF3840205CC0CD737F3F3456CF637B0F64D0EAA2B06
        tokenPrefix: Bearer
        header: Authorization
        expirationTimeout: 600000 # One Hour token
        minimumTimeout: 100000 # 10 minutes, minumum session duration before  require refresh/new token
      mongo:
        database: users