version: '3.7'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
  mongo_seed:
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command: /mongo-seed/import.sh
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"